
export const FEMALE_PROMPTS = [
  {
    id: 1,
    title: 'Kiểu 1 – Selfie Lồng Đèn',
    text: "Keep 100% of the character's face from the uploaded photo. A girl wearing an elegant, form-fitting ruby red satin dress with cherry red lipstick. Wavy hair down, sparkling eyes. Holding a traditional red lantern for a close-up selfie, lips slightly parted in a smile. Background is a row of high-hanging red lanterns with warm golden light. Vibe: cute – charming – Mid-Autumn Festival.",
  },
  {
    id: 2,
    title: 'Kiểu 2 – Cắn Bánh Trung Thu',
    text: "Keep 100% of the character's face from the uploaded photo. Half-body shot, a girl sits at a bamboo table, wearing a thigh-slit red satin dress, gently biting a mooncake, looking at the camera with a sweet gaze. Smokey reddish-brown eye makeup, glossy red lips. Background: bamboo table, tea, red and gold mooncake box. Golden hour lighting. Vibe: sweet – lifestyle – Mid-Autumn Festival.",
  },
  {
    id: 3,
    title: 'Kiểu 3 – Catwalk Đường Phố',
    text: "Keep 100% of the character's face from the uploaded photo. Full-body low angle, a girl catwalks on a lantern-lit street in Hoi An. Wearing a long, slit red satin dress, metallic high heels, and a diamond choker. High messy bun with a few loose strands. Gently lifting her dress, eyes looking straight ahead with confidence. Background: a sparkling street of red and yellow lanterns. Vibe: elegant – high fashion – Mid-Autumn Festival.",
  },
  {
    id: 4,
    title: 'Kiểu 4 – Ánh Trăng Sân Thượng',
    text: "Keep 100% of the character's face from the uploaded photo. Cinematic photo, a girl stands on a rooftop, wearing a metallic red satin dress, with the full moon behind her. Holding a red lantern high up to the sky, dress and hair flowing gently in the wind. An elegant posture. Background: city skyline with the Mid-Autumn moon. Vibe: magical – captivating – goddess.",
  },
  {
    id: 5,
    title: 'Kiểu 5 – Hồ Sen Tỏa Sáng',
    text: "Keep 100% of the character's face from the uploaded photo. Medium shot, a girl sits by a lotus pond, wearing a long, two-strap, thigh-slit red satin dress. Holding a mooncake, gazing into the distance. Background: a lotus pond reflecting the moonlight, lanterns hanging by the pond. Ethereal lighting, a mix of gold and silver. Vibe: captivating – poetic – Mid-Autumn Festival.",
  },
  {
    id: 6,
    title: 'Kiểu 6 – Đu Quay Lồng Đèn',
    text: "Keep 100% of the character's face from the uploaded photo. Dynamic photo, a girl sits on a swing adorned with red lanterns. Wearing a pinkish-red satin dress, gracefully leaning back. Half-up hairstyle, pinkish-red lips, glowing cheeks. Background: a garden full of red and pastel pink lanterns. Vibe: playful – graceful – Mid-Autumn Festival.",
  },
  {
    id: 7,
    title: 'Kiểu 7 – Ban Công Ngắm Trăng',
    text: "Keep 100% of the character's face from the uploaded photo. Full-body shot, a girl stands on a wooden balcony, wearing an off-the-shoulder, form-fitting red satin dress. Hands on the railing, looking at the full moon, long hair flowing gently. Background: lantern-lit street below, moonlight from above. Vibe: elegant – captivating – Mid-Autumn Festival.",
  },
  {
    id: 8,
    title: 'Kiểu 8 – Vườn Trà Rực Rỡ',
    text: "Keep 100% of the character's face from the uploaded photo. Lifestyle photo, a girl sits in a garden tea house, wearing a red satin dress with elegant hip cut-outs, holding a teacup with a bright smile. Background: bamboo tea table, mooncake box, red lanterns hanging from trees. Warm golden light. Vibe: friendly – elegant – lifestyle.",
  },
  {
    id: 9,
    title: 'Kiểu 9 – Cầu Thang Tỏa Sáng',
    text: "Keep 100% of the character's face from the uploaded photo. Cinematic, a girl stands on a wooden staircase, wearing a sparkling red sequin satin dress, reflecting the lantern light. Posed with a slight turn, one hand on the railing, the other brushing her hair. Ultra-sharp focus on the face. Vibe: fashionable – captivating – high fashion Mid-Autumn.",
  },
  {
    id: 10,
    title: 'Kiểu 10 – Nữ Hoàng Đêm Rằm',
    text: "Keep 100% of the character's face from the uploaded photo. Full-body photo, a girl stands in the middle of a brick courtyard, wearing a long-trained red satin gown and a diamond necklace. Hands spreading the dress slightly as it flows, with a strong, direct gaze. Background: a bright full moon high above, surrounded by hundreds of red lanterns. Vibe: powerful – Mid-Autumn queen – captivating.",
  },
  {
    id: 11,
    title: 'Kiểu 11 – Dạo Sông Thả Đèn',
    text: "Keep 100% of the character's face from the uploaded photo. Cinematic photo, a girl walks along the bank of the Hoi An river, wearing a form-fitting ruby red satin silk dress with a gently flowing slit. Holding a lantern to release on the river, with a gentle gaze following it. Background: hundreds of bright flower lanterns on the water, moonlight reflecting on the surface. Vibe: romantic – classic – Mid-Autumn Festival.",
  },
  {
    id: 12,
    title: 'Kiểu 12 – Cầu Tre Tỏa Sáng',
    text: "Keep 100% of the character's face from the uploaded photo. Full-body shot, a girl stands on a bamboo bridge over a lotus pond, wearing a golden-red satin dress, her hair gently blowing in the wind. One hand holding a mooncake, the other a lantern. Background: lotus pond reflecting the full moon, golden light on the bamboo bridge. Vibe: poetic – graceful – Mid-Autumn Festival.",
  },
  {
    id: 13,
    title: 'Kiểu 13 – Nét Cổ Tự',
    text: "Keep 100% of the character's face from the uploaded photo. Retro style, a girl stands before an ancient temple gate, wearing a modest red satin dress. Gently holding a red paper lantern, looking up at the high-hanging moon. Background: curved temple roof, ethereal incense smoke. Vibe: sacred – mysterious – Mid-Autumn Festival.",
  },
  {
    id: 14,
    title: 'Kiểu 14 – Vũ Điệu Đêm Trăng',
    text: "Keep 100% of the character's face from the uploaded photo. Dynamic photo, a girl spins and dances in a communal house courtyard, her flared red satin dress swirling. High ponytail with a few loose strands. Background: a bright full moon, the courtyard decorated with many red and orange lanterns. Vibe: artistic – vibrant – Mid-Autumn Festival.",
  },
  {
    id: 15,
    title: 'Kiểu 15 – Ánh Trăng Đỉnh Núi',
    text: "Keep 100% of the character's face from the uploaded photo. Cinematic photo, a girl stands on a mountaintop, wearing a silvery-red satin dress, holding a lantern high. Background: a sea of clouds, the full moon shining behind her. Vibe: majestic – goddess – Mid-Autumn Festival.",
  },
  {
    id: 16,
    title: 'Kiểu 16 – Múa Lân Sôi Động',
    text: "Keep 100% of the character's face from the uploaded photo. Half-body shot, a girl stands amidst a lion and dragon dance troupe, wearing a boldly designed red satin dress. Holding a mooncake, looking directly at the camera with a slight smile. Background: red and gold lions, vibrant lanterns. Vibe: lively – fashionable – Mid-Autumn Festival.",
  },
  {
    id: 17,
    title: 'Kiểu 17 – Duyên Dáng Cùng Quạt Giấy',
    text: "Keep 100% of the character's face from the uploaded photo. Lifestyle photo, a girl sits on a bamboo chair, wearing a slit red satin dress, holding a red paper fan covering half her face. Makeup emphasizes seductive smokey eyes. Background: old brick courtyard, lanterns hanging overhead. Vibe: mysterious – captivating – Mid-Autumn Festival.",
  },
  {
    id: 18,
    title: 'Kiểu 18 – Cổng Nguyệt Rực Rỡ',
    text: "Keep 100% of the character's face from the uploaded photo. Full-body shot, a girl stands under a circular moon gate, wearing a sparkling, stone-adorned red satin dress, holding her dress out. Background: a moon gate leading to a garden with red lanterns. Moonlight shines through. Vibe: powerful – elegant – Mid-Autumn Festival.",
  },
  {
    id: 19,
    title: 'Kiểu 19 – Vẻ Đẹp Hoa Đăng',
    text: "Keep 100% of the character's face from the uploaded photo. Cinematic photo, a girl sits in a small boat on a river, wearing a soft red satin dress, releasing a flower lantern onto the water. Background: hundreds of bright flower lanterns, the full moon reflected on the river. Vibe: dreamy – romantic – Mid-Autumn Festival.",
  },
  {
    id: 20,
    title: 'Kiểu 20 – Nữ Hoàng Lầu Vọng Nguyệt',
    text: "Keep 100% of the character's face from the uploaded photo. Full-body photo, a girl stands in a high wooden pavilion, wearing a mermaid-style red satin gown and a pearl necklace. Hand on the railing, looking down with a proud gaze. Background: a courtyard full of lanterns, the full moon shining behind. Vibe: powerful – queen – Mid-Autumn Festival.",
  },
  {
    id: 21,
    title: 'Kiểu 21 – Hằng Nga Cyberpunk',
    text: "Keep 100% of the character's face. A cyberpunk version of the Moon Goddess (Hằng Nga), wearing a modernized ao dai made of holographic material with red neon details. Glowing braided hair. Standing in the middle of a Saigon street in 2077 during Mid-Autumn Festival, filled with neon signs and flying drones carrying lanterns. Vibe: futuristic – high-tech – cool.",
  },
  {
    id: 22,
    title: 'Kiểu 22 – Phi Hành Gia & Mặt Trăng',
    text: "Keep 100% of the character's face. Hyper-realistic photo, a girl in a pearl-white astronaut suit, helmet off to reveal her beautiful face. Sitting on a moon rock, holding a mooncake from Earth. In the distance, the blue Earth is visible. Vibe: fantasy – poetic – epic.",
  },
  {
    id: 23,
    title: 'Kiểu 23 – Tương Tác Cùng Lân Robot',
    text: "Keep 100% of the character's face. Dynamic photo, a girl in red and black tech-wear, interacting with a giant, glowing robot lion. A look of curiosity and excitement. Background is a high-tech square with hologram screens. Vibe: energetic – modern – joyful.",
  },
  {
    id: 24,
    title: 'Kiểu 24 – Ngự Uyển Ảo',
    text: "Keep 100% of the character's face. Cinematic photo, a girl in a red satin gown, strolling through a virtual reality imperial garden. The trees glow, and lanterns are floating energy orbs. Her hand touches a hologram lotus flower. Vibe: magical – elegant – dreamlike.",
  },
  {
    id: 25,
    title: 'Kiểu 25 – Trình Diễn Lồng Đèn Drone',
    text: "Keep 100% of the character's face. Full-body photo, a girl stands on the rooftop of a skyscraper, with a drone show creating a giant lantern in the night sky behind her. Wearing a red sequin dress, hair blowing in the wind. A look of awe. Vibe: breathtaking – luxurious – modern.",
  },
  {
    id: 26,
    title: 'Kiểu 26 – Chùa Hologram',
    text: "Keep 100% of the character's face. A girl wears a transparent silk ao dai integrated with glowing optical fibers, standing before an ancient pagoda recreated by holograms. Holding a plasma lantern shaped like a lotus. Background mixes classic architecture with high-tech elements. Vibe: spiritual – futuristic – ethereal.",
  },
  {
    id: 27,
    title: 'Kiểu 27 – Tiệc Trà không Trọng Lực',
    text: "Keep 100% of the character's face. Cinematic photo, a girl in a stylized red spacesuit, floating in a space station compartment with a window looking out at a giant moon. The tea set and mooncakes are also floating gently. Vibe: fantasy – unique – gentle.",
  },
  {
    id: 28,
    title: 'Kiểu 28 – Kỵ Sĩ Lân Phát Quang Sinh Học',
    text: "Keep 100% of the character's face. Dynamic photo, a girl in tech-wear knight armor, riding a vibrant, bioluminescent lion-drone. Flying through the sky of a metropolis on Mid-Autumn night. A determined look. Vibe: strong – adventurous – epic.",
  },
  {
    id: 29,
    title: 'Kiểu 29 – Trung Thu Trên Sao Hỏa',
    text: "Keep 100% of the character's face. A girl stands in a biodome garden on Mars. Wearing a red evening gown, looking towards the distant blue Earth through the dome. The lanterns are glowing botanical spheres. Vibe: science fiction – solitary – romantic.",
  },
  {
    id: 30,
    title: 'Kiểu 30 – Vị Giác Tăng Cường',
    text: "Keep 100% of the character's face. Close-up shot, a girl wearing transparent AR glasses, tasting a piece of mooncake. The AR interface displays flavor information in front of her. A look of surprised delight. Vibe: high-tech – lifestyle – chic.",
  },
];

export const FEMALE_PROMPTS_V2 = [
  {
    id: 1,
    title: 'Kiểu 1 - Nữ Thần & Thỏ Ngọc',
    text: "Keep my real face exactly the same as in the uploaded photo, do not change any facial features. An artistic close-up Mid-Autumn Festival portrait with a bright, radiant background. A beautiful young Vietnamese woman with fair skin, high cheekbones, and a delicate jawline. Her hair flows in soft waves, crowned with a tall sparkling diamond tiara. She wears a haute couture golden satin gown inspired by the traditional yếm, with a refined halter cut-out neckline and embroidered golden lotus motifs adorned with crystals. She tenderly holds a real fluffy white rabbit in her arms, while gracefully turning her head to look directly into the camera with a gentle, radiant smile. Her expression conveys warmth, elegance, and festive charm. The framing focuses on her face, shoulders, hands, and the rabbit, capturing sharp, ultra-detailed features. The background remains intact but softly blurred, showing a low square bamboo table with golden mooncakes, colorful fruits, and a traditional brown ceramic teapot set. Glowing red, yellow, and green lanterns illuminate the scene, a black lacquer vase with peach blossoms and red berries decorates the side, and in the distance, lion dancers perform under the radiant full moon. Ultra-realistic 4K close-up, radiant cinematic lighting, dreamy and glamorous high-fashion editorial style."
  },
  {
    id: 2,
    title: 'Kiểu 2 - Góc Nghiêng Kiêu Kỳ',
    text: "Keep my real face exactly the same as in the uploaded photo, do not change any facial features. An artistic close-up Mid-Autumn Festival portrait with a bright radiant background. The camera captures the woman from behind at shoulder level, showcasing her elegant bare back with a shimmering golden satin border running down the spine. She gracefully turns her head over her shoulder, looking directly into the camera with a gentle, radiant smile. Her wavy dark brown hair cascades softly down her back, crowned with a tall sparkling diamond tiara. She wears a haute couture evening gown inspired by the traditional yếm, crafted from golden satin silk with embroidered lotus motifs and tiny crystals. In her arms, close to her chest, she tenderly holds a real fluffy white rabbit, enhancing the warmth and tenderness of the scene. The background remains intact but softly blurred: a low bamboo table with golden mooncakes, colorful fruits, and a traditional brown ceramic teapot set; glowing lanterns in red, yellow, and green; a black lacquer vase with peach blossoms and red berries; and the distant silhouette of lion dancers under the luminous full moon. Ultra-realistic 4K close-up, cinematic rim lighting, glamorous high-fashion editorial mood with a warm, festive charm"
  },
  {
    id: 3,
    title: 'Kiểu 3 - Yếm Vàng & Thỏ Trắng',
    text: "Keep my real face exactly the same as in the uploaded photo, do not change any facial features. A festive Mid-Autumn Festival indoor scene. A beautiful young Vietnamese woman with fair skin, an oval face, high cheekbones, and a delicate jawline. She has a serene yet subtly alluring expression, with dark brown hair styled in a neat low bun and a few soft strands framing her face. She has a graceful, feminine figure with a full, natural bust and a gentle cleavage that enhances her curves elegantly. She wears a luxurious haute couture evening gown inspired by the traditional yếm. The gown is crafted from premium silk satin in a shimmering golden hue. Its halter neckline is designed with an elegant cut-out that highlights her soft cleavage in a tasteful, natural way. The front bodice is hand-embroidered with radiant golden lotus motifs and adorned with tiny sparkling crystals, creating an exquisite, refined detail. The gown flows into a long, floor-length skirt with wide, graceful drapes that move fluidly, balancing sensuality with sophistication. She sits gracefully on a bamboo mat, gently holding a real fluffy white rabbit in her arms. In front of her is a low square bamboo table with a natural wooden surface. On the table are golden mooncakes, colorful sliced fruits, and a traditional brown ceramic teapot set with small teacups. Around her are glowing lanterns in red, yellow, and green, and a black lacquer vase filled with blossoming peach flowers and red berries. In the background, a lion dance performance takes place under a large glowing full moon, enhancing the festive spirit. The overall atmosphere is warm, dreamy, and celebratory, filled with the essence of the Mid-Autumn Festival. Cinematic lighting, ultra-realistic 4K photography, sharp details, rich red and golden tones"
  },
  {
    id: 4,
    title: 'Kiểu 4 - Duyên Dáng Bên Lồng Đèn',
    text: "Keep my real face exactly the same as in the uploaded photo, do not change any facial features. A cinematic half-body to full-body portrait during the Mid-Autumn Festival with a bright, radiant background. A beautiful young Vietnamese woman stands elegantly beside a bamboo table, her body slightly turned to the side. One hand gracefully holds a red lantern hanging low, while the other gently cradles a real fluffy white rabbit against her chest. Her posture is poised and refined, her gaze turned slightly away, exuding confidence and allure. She wears a haute couture evening gown inspired by the traditional yếm, made of shimmering golden satin silk. The halter neckline features a tasteful cut-out that accentuates her cleavage. The bodice is hand-embroidered with golden lotus motifs and adorned with sparkling crystals. The golden satin fabric flows luxuriously in a long skirt, draping softly around her figure, balancing sensuality with elegance. Beside her, the bamboo table displays golden mooncakes, colorful sliced fruits, and a traditional brown ceramic teapot set. In the brightly illuminated background, glowing red, yellow, and green lanterns shine vividly. A black lacquer vase filled with peach blossoms and red berries adds festive beauty, while the silhouette of a lion dance performance unfolds under a radiant full moon. The scene is cinematic, dreamy, and celebratory, with vibrant tones of red and gold bringing the Mid-Autumn Festival spirit to life. Ultra-realistic 4K, sharp details, radiant festival lighting, glamorous editorial vibe, bright dreamy background"
  },
  {
    id: 5,
    title: 'Kiểu 5 - Thơ Mộng Tựa Bàn Trà',
    text: "Keep my real face exactly the same as in the uploaded photo, do not change any facial features. A cinematic half-body portrait during the Mid-Autumn Festival with a bright, radiant background. A beautiful young Vietnamese woman sits gracefully, leaning slightly against a bamboo table. One hand rests gently on the edge of the table, while the other cradles a real fluffy white rabbit close to her chest. Her posture is relaxed yet elegant, with her gaze softly turned into the distance, blending allure and refinement. She wears a haute couture evening gown inspired by the traditional yếm, crafted from shimmering golden satin silk. The halter neckline features an elegant cut-out that tastefully highlights her cleavage. The bodice is hand-embroidered with radiant golden lotus motifs and sparkling crystals. The golden satin fabric flows luxuriously in soft folds, combining sensuality with sophistication. In front of her, the bamboo table displays golden mooncakes, a tray of colorful fruits, and a traditional brown ceramic teapot set. In the brightly illuminated background, glowing lanterns in red, yellow, and green shine vividly, a black lacquer vase filled with peach blossoms and red berries decorates the festive setting, and the silhouette of a lion dance performance takes place under the radiant full moon. The warm, glowing atmosphere feels dreamy, celebratory, and cinematic. Ultra-realistic 4K, half-body composition, sharp details, radiant festival lighting, bright dreamy background with rich red and golden tones. "
  },
  {
    id: 6,
    title: 'Kiểu 6 - Nữ Hoàng Đêm Trăng',
    text: "Keep my real face exactly the same as in the uploaded photo, do not change any facial features. A cinematic full-body Mid-Autumn Festival portrait with a bright radiant background. A beautiful young Vietnamese woman with fair skin, high cheekbones, and a delicate jawline. Her hair flows in soft waves down her back, adorned with a tall diamond tiara sparkling under the lantern light. She wears a haute couture evening gown inspired by the traditional yếm, crafted from shimmering golden satin silk. The halter neckline features a refined cut-out highlighting her cleavage. The bodice is embroidered with radiant golden lotus motifs and crystals, while the gown cascades into a long, voluminous skirt that spreads wide and luxurious across the ground. The gown is designed with an open back, but along the spine runs a narrow golden satin border from the neckline down to the waist, shimmering elegantly under the light. This detail adds sophistication and refinement, balancing sensuality with grace. She turns her head gracefully over her shoulder, gently holding a real fluffy white rabbit as their eyes meet in a tender, emotional gaze. Beside her is a low square bamboo table with a rustic wooden surface, arranged with golden mooncakes, colorful sliced fruits, and a traditional brown ceramic teapot set. Surrounding the scene are glowing red, yellow, and green lanterns, and a black lacquer vase filled with peach blossoms and red berries. In the background, lion dancers perform beneath the luminous full moon. Ultra-realistic 4K, radiant rim lighting outlining her figure, flowing golden silk textures, glamorous high-fashion editorial mood. "
  },
  {
    id: 7,
    title: 'Kiểu 7 - Dáng Ngọc Dưới Trăng',
    text: "Keep my real face exactly the same as in the uploaded photo, do not change any facial features. A cinematic full-body portrait during the Mid-Autumn Festival with a bright radiant background. A beautiful young Vietnamese woman is photographed from behind, walking gracefully toward the glowing full moon. Her long legs appear endless in the dramatic low-back perspective. She wears a haute couture evening gown inspired by the traditional yếm, made of shimmering golden satin silk with a refined halter cut-out neckline that highlights her curves. The gown is hand-embroidered with golden lotus motifs and sparkling crystals, flowing into a wide, floor-length skirt that spreads luxuriously across the ground. She turns her head elegantly over her shoulder, looking back toward the camera with a tender gaze. On her shoulder rests a real fluffy white rabbit, its eyes meeting hers affectionately. One hand is lifted softly, caressing the rabbit with warmth and tenderness. In the bright background, radiant red, yellow, and green lanterns glow vividly, a black lacquer vase with peach blossoms and red berries decorates the scene, and the silhouette of a lion dance troupe performs beneath the luminous full moon. The cinematic rim lighting outlines her figure and gown, creating a divine, goddess-like aura. Ultra-realistic 4K, sharp details, radiant festival lighting, flowing silk textures, dreamy and glamorous high-fashion editorial style. "
  },
  {
    id: 8,
    title: 'Kiểu 8 - Sải Bước Catwalk',
    text: "Keep my real face exactly the same as in the uploaded photo, do not change any facial features. A festive Mid-Autumn Festival indoor scene. A beautiful young Vietnamese woman with fair skin, an oval face, high cheekbones, and a delicate jawline. She has a confident, alluring expression, with dark brown hair styled in a neat low bun and soft strands framing her face. She has a graceful, feminine figure with a full, natural bust and a gentle cleavage that enhances her curves elegantly. She wears a luxurious haute couture evening gown inspired by the traditional yếm, crafted from shimmering golden satin silk. The halter neckline features a refined cut-out that highlights her cleavage in a tasteful way. The bodice is embroidered with radiant golden lotus motifs and sparkling crystals, while the floor-length gown flows in wide drapes with a high slit, balancing sensuality with sophistication. She is captured in a mid-step walking pose beside a bamboo table, as if on a runway. Her right arm cradles a real fluffy white rabbit against her chest, while her eyes gaze straight into the camera with intensity and elegance. The slit of her gown reveals her slender legs, and the flowing golden fabric flutters gently, glowing under the lantern light. This pose radiates high-fashion editorial energy, blending cultural festivity with luxury couture. On the bamboo table are golden mooncakes, sliced fruits, and a traditional brown ceramic teapot set. Surrounding her are glowing lanterns in red, yellow, and green, and a black lacquer vase filled with blossoming peach flowers and red berries. In the background, a lion dance performance unfolds beneath the large glowing full moon, enhancing the cinematic festive spirit. The overall mood is bold, luxurious, and celebratory, like a high-fashion magazine cover under the Mid-Autumn Festival theme. Ultra-realistic 4K photography, sharp details, dramatic runway lighting, rich red and golden tones. "
  },
  {
    id: 9,
    title: 'Kiểu 9 - Bìa Tạp Chí Vogue',
    text: "Keep my real face exactly the same as in the uploaded photo, do not change any facial features. A festive Mid-Autumn Festival indoor scene. A beautiful young Vietnamese woman with fair skin, an oval face, high cheekbones, and a delicate jawline. She has a confident, alluring expression, with dark brown hair styled in a neat low bun and a few soft strands framing her face. She has a graceful, feminine figure with a full, natural bust and gentle cleavage that enhances her curves elegantly. She wears a luxurious haute couture evening gown inspired by the traditional yếm, made of shimmering golden satin silk. The halter neckline features an elegant cut-out that tastefully highlights her cleavage. The bodice is embroidered with golden lotus motifs and sparkling crystals, and the floor-length skirt drapes fluidly, blending sensuality with sophistication. She stands in a graceful ¾ turned pose, her body slightly angled to the side. One hand gently lifts to touch her hair, while the other arm cradles a real fluffy white rabbit close to her chest. The lantern light reflects softly on her bustline, making her cleavage glow subtly. She wears a half-smile — poised, confident, and elegant — exuding the aura of a Vogue magazine cover. Beside her is a low bamboo table with golden mooncakes, colorful sliced fruits, and a traditional brown ceramic teapot set. Surrounding her are glowing lanterns in red, yellow, and green, and a black lacquer vase filled with blossoming peach flowers and red berries. In the background, a lion dance unfolds beneath the large glowing full moon, amplifying the festive cinematic mood. The overall scene is glamorous, cinematic, and editorial, filled with sensual elegance and the celebratory spirit of the Mid-Autumn Festival. Ultra-realistic 4K, sharp details, dramatic lantern lighting, rich red and golden tones. "
  },
  {
    id: 10,
    title: 'Kiểu 10 - Nét Đẹp Bí Ẩn',
    text: "Keep my real face exactly the same as in the uploaded photo, do not change any facial features. An artistic half-face close-up portrait during the Mid-Autumn Festival. A beautiful young Vietnamese woman with fair skin, high cheekbones, and a delicate jawline. The camera frames only half of her face and half of the real fluffy white rabbit she is holding, creating a mysterious, editorial composition. She wears a haute couture evening gown inspired by the traditional yếm, crafted from shimmering golden satin silk with a halter neckline, golden lotus embroidery, and sparkling crystal details. The gown’s golden tones shimmer softly in the lantern light, adding depth and refinement. Her visible eye gazes confidently into the camera, lips slightly curved into a subtle half-smile, exuding allure and elegance. The details of her skin, the rabbit’s fur, and the embroidery of the gown are captured in ultra-sharp focus. In the softly blurred background are glowing red lanterns and the large full moon shining faintly, casting an ethereal glow. The dreamy bokeh effect creates a cinematic, high-fashion editorial vibe — perfect for a Vogue magazine cover. Ultra-realistic 4K, sharp facial details, cinematic lantern lighting, artistic composition, rich tones of red and gold. "
  },
  {
    id: 11,
    title: 'Kiểu 11 - Nữ Thần Hướng Trăng',
    text: "Keep my real face exactly the same as in the uploaded photo, do not change any facial features. A cinematic full-body portrait during the Mid-Autumn Festival with a bright, radiant background. The camera captures the woman from a low-angle shot, looking upward toward the glowing full moon. This perspective enhances her height and elegance, making her appear powerful and majestic, like a moon goddess. She wears a haute couture evening gown inspired by the traditional yếm, crafted from shimmering golden satin silk. The halter neckline features a tasteful cut-out that accentuates her cleavage. The bodice is embroidered with radiant golden lotus motifs and adorned with sparkling crystals. The golden satin fabric flows into a long skirt, draping luxuriously with a sense of motion and refinement. Her head is tilted slightly upward, chin lifted gracefully, her expression serene yet commanding. In her arms, she gently cradles a real fluffy white rabbit, its fur glowing softly under the lantern light. In the brightly illuminated background, radiant red, yellow, and green lanterns glow vividly, a black lacquer vase holds peach blossoms and red berries, and the silhouette of a lion dance troupe performs under the luminous full moon. The radiant lighting creates a festive, cinematic, and high-fashion editorial mood. Ultra-realistic 4K, sharp low-angle perspective, radiant festival lighting, glamorous and divine atmosphere, bright dreamy background with rich tones of red and gold. "
  },
  {
    id: 12,
    title: 'Kiểu 12 - Quyền Lực & Quý Phái',
    text: "Keep my real face exactly the same as in the uploaded photo, do not change any facial features. A festive Mid-Autumn Festival indoor scene. A beautiful young Vietnamese woman with fair skin, an oval face, high cheekbones, and a delicate jawline. She has a serene yet subtly alluring expression, with dark brown hair styled in a neat low bun and a few soft strands framing her face. She has a graceful, feminine figure with a full, natural bust and a gentle cleavage that enhances her curves elegantly. She wears a luxurious haute couture evening gown inspired by the traditional yếm. The gown is crafted from premium silk satin in a shimmering golden hue. Its halter neckline is designed with an elegant cut-out that highlights her soft cleavage in a tasteful, natural way. The front bodice is hand-embroidered with radiant golden lotus motifs and adorned with tiny sparkling crystals. The gown flows into a long, floor-length skirt with wide, graceful drapes, balancing sensuality with sophistication. She is sitting regally on a wooden chair beside a bamboo table, her legs crossed gracefully. One hand rests lightly on her thigh, while the other arm gently holds a real fluffy white rabbit close to her chest. Her back is straight, her chin slightly lifted, radiating a noble and powerful aura, like a queen under the full moon. On the bamboo table are golden mooncakes, colorful sliced fruits, and a traditional brown ceramic teapot set with small teacups. Around her are glowing lanterns in red, yellow, and green, and a black lacquer vase filled with blossoming peach flowers and red berries. In the background, a lion dance performance takes place under a large glowing full moon, adding vibrance and festivity to the scene. The overall atmosphere is warm, dreamy, and celebratory, filled with the essence of the Mid-Autumn Festival. Cinematic lighting, ultra-realistic 4K photography, sharp details, rich red and golden tones. "
  },
  {
    id: 13,
    title: 'Kiểu 13 - Duyên Dáng Tựa Bàn Trà',
    text: "Keep my real face exactly the same as in the uploaded photo, do not change any facial features. A cinematic half-body portrait during the Mid-Autumn Festival with a bright, radiant background. A beautiful young Vietnamese woman sits gracefully, leaning slightly against a bamboo table. One hand rests gently on the edge of the table, while the other cradles a real fluffy white rabbit close to her chest. Her posture is relaxed yet elegant, with her gaze softly turned into the distance, blending allure and refinement. She wears a haute couture evening gown inspired by the traditional yếm, crafted from shimmering golden satin silk. The halter neckline features an elegant cut-out that tastefully highlights her cleavage. The bodice is hand-embroidered with radiant golden lotus motifs and sparkling crystals. The golden satin fabric flows luxuriously in soft folds, combining sensuality with sophistication. In front of her, the bamboo table displays golden mooncakes, a tray of colorful fruits, and a traditional brown ceramic teapot set. In the brightly illuminated background, glowing lanterns in red, yellow, and green shine vividly, a black lacquer vase filled with peach blossoms and red berries decorates the festive setting, and the silhouette of a lion dance performance takes place under the radiant full moon. The warm, glowing atmosphere feels dreamy, celebratory, and cinematic. Ultra-realistic 4K, half-body composition, sharp details, radiant festival lighting, bright dreamy background with rich red and golden tones. "
  },
  {
    id: 14,
    title: 'Kiểu 14 - Tiên Nữ Đêm Rằm',
    text: "Keep my real face exactly the same as in the uploaded photo, do not change any facial features. A cinematic full-body Mid-Autumn Festival portrait with a bright radiant background. A beautiful young Vietnamese woman with fair skin, an oval face, high cheekbones, and a delicate jawline. Her hair is styled in soft flowing waves cascading down her back, crowned with a tall, elegant diamond tiara that sparkles under the lantern light, enhancing her regal goddess-like aura. She wears a haute couture evening gown inspired by the traditional yếm, crafted from shimmering golden satin silk. The halter neckline features a refined cut-out that tastefully highlights her cleavage. The bodice is embroidered with radiant golden lotus motifs and adorned with sparkling crystals, while the gown flows into a long, voluminous skirt with wide drapes that spill dramatically across the floor, creating endless, graceful lines. She turns her head gracefully over her shoulder, holding a real fluffy white rabbit tenderly. Their eyes meet in a soft, affectionate gaze, creating a poetic and emotional connection. In the brightly illuminated background, glowing red, yellow, and green lanterns, a black lacquer vase with peach blossoms and red berries, and the silhouette of lion dancers performing beneath the luminous full moon set a dreamy festive atmosphere. Rim lighting outlines her silhouette and gown, amplifying her divine, high-fashion presence. Ultra-realistic 4K, radiant festival lighting, sharp details, glamorous haute couture styling, dreamy artistic editorial mood. "
  },
  {
    id: 15,
    title: 'Kiểu 15 - Vẻ Đẹp E Ấp',
    text: "Keep my real face exactly the same as in the uploaded photo, do not change any facial features. A festive Mid-Autumn Festival indoor scene. A beautiful young Vietnamese woman with fair skin, an oval face, high cheekbones, and a delicate jawline. She has a serene yet alluring expression, with dark brown hair styled in a neat low bun and a few soft strands framing her face. She has a graceful, feminine figure with a full, natural bust and a gentle cleavage that enhances her curves elegantly. She wears a luxurious haute couture evening gown inspired by the traditional yếm, made of shimmering golden satin silk. The halter neckline features a tasteful cut-out that highlights her cleavage naturally. The bodice is embroidered with golden lotus motifs and delicate sparkling crystals, while the floor-length skirt flows in graceful drapes with a high slit, combining sensuality with sophistication. She is sitting casually on a bamboo mat, one leg stretched out and the other bent slightly, revealing her elegant curves. A real fluffy white rabbit rests gently on her lap as her hand softly caresses it. The gown’s flowing fabric spreads across the bamboo mat around her, glowing under the lantern light. Her face is illuminated by the warm glow, her dreamy eyes gazing softly, radiating an aura that feels both intimate and sensual. Around her are glowing lanterns in red, yellow, and green, and a black lacquer vase filled with blossoming peach flowers and red berries. In front of her is a low bamboo table with golden mooncakes, colorful sliced fruits, and a traditional brown ceramic teapot set. In the background, a lion dance performance takes place under the large glowing full moon, filling the space with vibrance and festivity. The overall mood is warm, intimate, and cinematic — close, natural, yet alluring. Ultra-realistic 4K, sharp details, dramatic lantern lighting, rich red and golden tones. "
  },
  {
    id: 16,
    title: 'Kiểu 16 - Quyền Lực & Tự Tin',
    text: "Keep my real face exactly the same as in the uploaded photo, do not change any facial features. A festive Mid-Autumn Festival indoor scene, framed in a half-body shot from the waist up. A beautiful young Vietnamese woman with fair skin, an oval face, high cheekbones, and a delicate jawline. She has a confident, alluring expression, with dark brown hair styled in a neat low bun and soft strands framing her face. She has a graceful, feminine figure with a natural full bust and a gentle cleavage that enhances her curves elegantly. She wears a luxurious haute couture evening gown inspired by the traditional yếm, crafted from shimmering golden satin silk. The halter neckline has a refined cut-out that highlights her cleavage tastefully. The bodice is embroidered with radiant golden lotus motifs and delicate sparkling crystals, while the flowing fabric exudes elegance and sophistication. She stands tall, one hand gently stroking a real fluffy white rabbit close to her chest, while the other hand rests confidently on her hip. Her gaze is locked directly at the camera, with a subtle half-smile on her lips, radiating power, confidence, and high-fashion energy — like a Vogue magazine cover. Behind her are glowing lanterns in red, yellow, and green, casting warm light across her face and gown. A black lacquer vase filled with peach blossoms and red berries adds a festive detail. In the distant background, a lion dance unfolds under a large glowing full moon, enhancing the vibrant Mid-Autumn Festival atmosphere. The overall mood is bold, cinematic, and luxurious, blending the celebratory spirit of the festival with the aura of high-fashion editorial photography. Ultra-realistic 4K, sharp details, dramatic lantern lighting, rich red and golden tones. "
  },
  {
    id: 17,
    title: 'Kiểu 17 - Nửa Vầng Trăng',
    text: "Keep my real face exactly the same as in the uploaded photo, do not change any facial features. An artistic half-face close-up portrait during the Mid-Autumn Festival. A beautiful young Vietnamese woman with fair skin, high cheekbones, and a delicate jawline. The camera frames only half of her face and half of the real fluffy white rabbit she is holding, creating a mysterious, editorial composition. She wears a haute couture evening gown inspired by the traditional yếm, crafted from shimmering golden satin silk with a halter neckline, golden lotus embroidery, and sparkling crystal details. The gown’s golden tones shimmer softly in the lantern light, adding depth and refinement. Her visible eye gazes confidently into the camera, lips slightly curved into a subtle half-smile, exuding allure and elegance. The details of her skin, the rabbit’s fur, and the embroidery of the gown are captured in ultra-sharp focus. In the softly blurred background are glowing red lanterns and the large full moon shining faintly, casting an ethereal glow. The dreamy bokeh effect creates a cinematic, high-fashion editorial vibe — perfect for a Vogue magazine cover. Ultra-realistic 4K, sharp facial details, cinematic lantern lighting, artistic composition, rich tones of red and gold. "
  },
  {
    id: 18,
    title: 'Kiểu 18 - Thần Thái Nữ Thần',
    text: "Keep my real face exactly the same as in the uploaded photo, do not change any facial features. A cinematic portrait taken during the Mid-Autumn Festival with a bright, radiant background. A beautiful young Vietnamese woman with fair skin, high cheekbones, and a delicate jawline. She gazes gracefully, her head turned at a divine angle that enhances her profile. She wears a haute couture evening gown inspired by the traditional yếm, made of shimmering golden satin silk. The halter neckline features a refined cut-out that highlights her cleavage. The bodice is hand-embroidered with radiant golden lotus motifs and sparkling crystals. The golden fabric drapes fluidly and luxuriously, blending sensuality with elegance. She gently cradles a real fluffy white rabbit close to her chest. The focus remains on her expression, gown, and the rabbit, captured with ultra-sharp details. In the brightly illuminated background, glowing lanterns in red, yellow, and green shine vibrantly, a black lacquer vase holds peach blossoms and red berries, and the silhouette of a lion dance appears beneath a luminous full moon. The bright festival lighting creates a celebratory and glamorous mood, balancing clarity with cinematic artistry. Ultra-realistic 4K, radiant lighting, crisp background details, vibrant festive tones of red and gold, bright dreamy atmosphere. "
  },
  {
    id: 19,
    title: 'Kiểu 19 - Đường Cong Quyến Rũ',
    text: "Keep my real face exactly the same as in the uploaded photo, do not change any facial features. A festive Mid-Autumn Festival indoor scene. A beautiful young Vietnamese woman with fair skin, an oval face, high cheekbones, and a delicate jawline. She has a serene yet alluring expression, with dark brown hair styled in a neat low bun and a few soft strands framing her face. She has a graceful, feminine figure with a full, natural bust and a gentle cleavage that enhances her curves elegantly. She wears a luxurious haute couture evening gown inspired by the traditional yếm, made of shimmering golden satin silk. The halter neckline features a tasteful cut-out that highlights her cleavage naturally. The bodice is embroidered with golden lotus motifs and sparkling crystals, while the long flowing skirt drapes gracefully with a high slit, balancing sensuality with sophistication. She is sitting sideways on a wooden chair, her back arching slightly in a soft curve that highlights her silhouette. One leg is crossed loosely over the other, and the long gown falls to the side, revealing the high slit in a refined, sensual way. A real fluffy white rabbit rests on her lap as she gently cradles it with her arm. Her gaze drifts into the distance with a dreamy, elegant expression — alluring yet tasteful. Beside her is a low bamboo table with golden mooncakes, colorful sliced fruits, and a traditional brown ceramic teapot set. Around her are glowing lanterns in red, yellow, and green, and a black lacquer vase filled with blossoming peach flowers and red berries. In the background, a lion dance performance unfolds beneath the large glowing full moon, adding vibrance and festivity. The overall atmosphere is warm, dreamy, and cinematic, filled with the essence of the Mid-Autumn Festival. Ultra-realistic 4K photography, sharp details, rich red and golden tones, dramatic lantern lighting. "
  },
  {
    id: 20,
    title: 'Kiểu 20 - Ánh Mắt Mộng Mơ',
    text: "Keep my real face exactly the same as in the uploaded photo, do not change any facial features. An artistic close-up Mid-Autumn Festival portrait with a bright radiant background. The camera captures the woman from behind at shoulder level, showing her elegant bare back with a shimmering golden satin border running down the spine. She gracefully turns her head over her shoulder to face the camera, her wavy dark brown hair cascading down, crowned with a tall sparkling diamond tiara. She wears a luxurious haute couture evening gown inspired by the traditional yếm, crafted from golden satin silk with embroidered lotus motifs and tiny crystals. In her arms, close to her chest, she tenderly holds a real fluffy white rabbit, her eyes gazing at it lovingly, creating an emotional, poetic connection. The background remains intact but softly blurred: a low bamboo table with golden mooncakes, colorful fruits, and a traditional brown ceramic teapot set; glowing lanterns in red, yellow, and green; a black lacquer vase with peach blossoms and red berries; and the distant silhouette of lion dancers under the radiant full moon. Ultra-realistic 4K close-up, cinematic rim lighting, glamorous and dreamy high-fashion editorial style. "
  },
  {
    id: 21,
    title: 'Kiểu 21 - Nét Đẹp Tinh Tế',
    text: "Keep my real face exactly the same as in the uploaded photo, do not change any facial features. A festive Mid-Autumn Festival indoor scene, framed in a half-body shot from the waist up. A beautiful young Vietnamese woman with fair skin, an oval face, high cheekbones, and a delicate jawline. She has a dreamy yet alluring expression, with dark brown hair styled in a neat low bun while a few strands fall loosely to frame her face. She has a graceful, feminine figure with a natural full bust and a gentle cleavage that enhances her curves elegantly. She wears a luxurious haute couture evening gown inspired by the traditional yếm, crafted from shimmering golden satin silk. The halter neckline features an elegant cut-out that tastefully highlights her cleavage. The bodice is embroidered with radiant golden lotus motifs and sparkling crystals, while the flowing golden fabric drapes gracefully, balancing sensuality with sophistication. She is posed in a ¾ turned angle, her shoulder slightly tilted to create a refined silhouette. One hand gently brushes through her loose strands of hair, while the other arm cradles a real fluffy white rabbit close to her chest. Lantern light softly illuminates her bustline, making her cleavage glow subtly — sensual yet elegant, never excessive. Her half-smile and serene gaze radiate confidence and high-fashion allure. Behind her are glowing lanterns in red, yellow, and green, casting warm festive light. A black lacquer vase filled with peach blossoms and red berries adds seasonal detail. In the distant background, a lion dance unfolds beneath a large glowing full moon, heightening the cinematic festive atmosphere. The overall mood is warm, sensual, and sophisticated — blending the celebratory spirit of the Mid-Autumn Festival with the elegance of a fashion editorial. Ultra-realistic 4K, sharp details, cinematic lantern lighting, rich red and golden tones. "
  },
  {
    id: 22,
    title: 'Kiểu 22 - Nụ Cười Tỏa Nắng',
    text: "Keep my real face exactly the same as in the uploaded photo, do not change any facial features. An artistic close-up Mid-Autumn Festival portrait with a bright, radiant background. A beautiful young Vietnamese woman with fair skin, high cheekbones, and a delicate jawline. Her hair flows in soft waves, crowned with a tall sparkling diamond tiara. She wears a haute couture golden satin gown inspired by the traditional yếm, with a refined halter cut-out neckline and embroidered golden lotus motifs adorned with crystals. She holds a real fluffy white rabbit tenderly in her arms, gazing at it with loving eyes, creating an emotional and poetic moment. The framing focuses on her face, shoulders, hands, and the rabbit, capturing sharp, ultra-detailed features. The background remains intact but softly blurred, showing a low square bamboo table with golden mooncakes, colorful fruits, and a traditional brown ceramic teapot set. Glowing red, yellow, and green lanterns illuminate the scene, a black lacquer vase with peach blossoms and red berries decorates the side, and in the distance, lion dancers perform under the radiant full moon. Ultra-realistic 4K close-up, radiant cinematic lighting, dreamy and glamorous high-fashion editorial style. "
  },
  {
    id: 23,
    title: 'Kiểu 23 - Dáng Vẻ Kiêu Sa',
    text: "Keep my real face exactly the same as in the uploaded photo, do not change any facial features. A festive Mid-Autumn Festival indoor scene. A beautiful young Vietnamese woman with fair skin, an oval face, high cheekbones, and a delicate jawline. She has a serene yet subtly alluring expression, with dark brown hair styled in a neat low bun and a few soft strands framing her face. She has a graceful, feminine figure with a full, natural bust and a gentle cleavage that enhances her curves elegantly. She wears a luxurious haute couture evening gown inspired by the traditional yếm, made of shimmering golden satin silk. The halter neckline features an elegant cut-out that highlights her cleavage in a tasteful way. The bodice is embroidered with radiant golden lotus motifs and sparkling crystals, and the long skirt flows to the floor in graceful drapes, balancing sensuality with sophistication. She leans slightly against a low bamboo table, her left hand resting lightly on its edge, her body relaxed. Her right arm holds a real fluffy white rabbit close to her chest. Her gaze drifts dreamily into the distance, her aura both sensual and refined. On the bamboo table are golden mooncakes, sliced colorful fruits, and a traditional brown ceramic teapot set. Surrounding her are glowing lanterns in red, yellow, and green, and a black lacquer vase filled with blossoming peach flowers and red berries. In the background, a lion dance performance takes place beneath the large glowing full moon, adding vibrance and festivity. The overall mood is warm, dreamy, and celebratory, filled with the essence of the Mid-Autumn Festival. Cinematic lighting, ultra-realistic 4K photography, sharp details, rich red and golden tones. "
  },
  {
    id: 24,
    title: 'Kiểu 24 - Duyên Dáng Cầm Đèn',
    text: "Keep my real face exactly the same as in the uploaded photo, do not change any facial features. A cinematic half-body to full-body portrait during the Mid-Autumn Festival with a bright, radiant background. A beautiful young Vietnamese woman stands elegantly beside a bamboo table, her body slightly turned to the side. One hand gracefully holds a red lantern hanging low, while the other gently cradles a real fluffy white rabbit against her chest. Her posture is poised and refined, her gaze turned slightly away, exuding confidence and allure. She wears a haute couture evening gown inspired by the traditional yếm, made of shimmering golden satin silk. The halter neckline features a tasteful cut-out that accentuates her cleavage. The bodice is hand-embroidered with golden lotus motifs and adorned with sparkling crystals. The golden satin fabric flows luxuriously in a long skirt, draping softly around her figure, balancing sensuality with elegance. Beside her, the bamboo table displays golden mooncakes, colorful sliced fruits, and a traditional brown ceramic teapot set. In the brightly illuminated background, glowing red, yellow, and green lanterns shine vividly. A black lacquer vase filled with peach blossoms and red berries adds festive beauty, while the silhouette of a lion dance performance unfolds under a radiant full moon. The scene is cinematic, dreamy, and celebratory, with vibrant tones of red and gold bringing the Mid-Autumn Festival spirit to life. Ultra-realistic 4K, sharp details, radiant festival lighting, glamorous editorial vibe, bright dreamy background. "
  },
  {
    id: 25,
    title: 'Kiểu 25 - Nữ Hoàng Quyền Lực',
    text: "Keep my real face exactly the same as in the uploaded photo, do not change any facial features. A cinematic full-body portrait during the Mid-Autumn Festival with a bright, radiant background. A beautiful young Vietnamese woman sits elegantly on a wooden chair, crossing her legs gracefully in a poised and queenly manner. One hand rests lightly on her thigh while the other cradles a real fluffy white rabbit close to her chest. Her back is straight, chin slightly lifted, and she gazes forward with a confident half-smile, exuding authority, charm, and high-fashion elegance. She wears a haute couture evening gown inspired by the traditional yếm, made of shimmering golden satin silk. The halter neckline has a refined cut-out that tastefully highlights her cleavage. The bodice is hand-embroidered with golden lotus motifs and sparkling crystals. The golden satin fabric cascades luxuriously into a floor-length skirt, enhancing her curves with both sensuality and refinement. Next to her, a bamboo table is set with golden mooncakes, colorful fresh fruits, and a traditional brown ceramic teapot set. In the brightly illuminated background, vibrant red, yellow, and green lanterns glow vividly, a black lacquer vase holds peach blossoms and red berries, and the silhouette of a lion dance troupe performs beneath the radiant full moon. The overall scene is cinematic, festive, and glamorous, with brilliant tones of red and gold capturing the lively spirit of the Mid-Autumn Festival. Ultra-realistic 4K, sharp details, radiant festival lighting, luxurious editorial vibe, bright dreamy background. "
  },
  {
    id: 26,
    title: 'Kiểu 26 - Ánh Mắt Mê Hoặc',
    text: "Keep my real face exactly the same as in the uploaded photo, do not change any facial features. An artistic close-up portrait during the Mid-Autumn Festival with a bright, radiant background. A beautiful young Vietnamese woman with fair skin, high cheekbones, and a delicate jawline. She gazes lovingly into the eyes of a real fluffy white rabbit that she tenderly holds in her hands against her chest. Their eyes meet in a soft, affectionate exchange, creating a poetic and emotional atmosphere. She wears a haute couture evening gown inspired by the traditional yếm, crafted from shimmering golden satin silk. The halter neckline features a refined cut-out that tastefully highlights her cleavage. The bodice is embroidered with radiant golden lotus motifs and adorned with sparkling crystals, while the golden satin fabric drapes luxuriously in soft folds, balancing sensuality with elegance. The composition focuses on her face, hands, and the rabbit, capturing ultra-sharp details of her expression, skin texture, and the rabbit’s fur. In the brightly illuminated background, glowing red, yellow, and green lanterns shine vividly, a black lacquer vase holds peach blossoms and red berries, and the silhouette of a lion dance appears beneath the radiant full moon. The bright festive light creates a dreamy, cinematic, and high-fashion atmosphere. Ultra-realistic 4K close-up, radiant lighting, sharp details, bright dreamy background, artistic editorial mood. "
  },
  {
    id: 27,
    title: 'Kiểu 27 - Nữ Thần Tỏa Sáng',
    text: "Keep my real face exactly the same as in the uploaded photo, do not change any facial features. A cinematic half-body to full-body portrait during the Mid-Autumn Festival with a bright, radiant background. A beautiful young Vietnamese woman stands elegantly beside a bamboo table, her body slightly turned to the side. One hand gracefully holds a red lantern hanging low, while the other gently cradles a real fluffy white rabbit against her chest. Her posture is poised and refined, her gaze turned slightly away, exuding confidence and allure. She wears a haute couture evening gown inspired by the traditional yếm, made of shimmering golden satin silk. The halter neckline features a refined cut-out that tastefully highlights her cleavage. The bodice is embroidered with radiant golden lotus motifs and adorned with sparkling crystals. The golden satin fabric drapes fluidly in a floor-length skirt, enhancing her curves with elegance and sophistication. Beside her, a bamboo table displays golden mooncakes, colorful fruits, and a traditional brown ceramic teapot set. In the brightly illuminated background, glowing lanterns in red, yellow, and green shine vibrantly, a black lacquer vase filled with peach blossoms and red berries decorates the festive scene, and the silhouette of a lion dance performance appears beneath a radiant full moon. The bright festival lighting makes the entire atmosphere celebratory, glamorous, and cinematic, while she remains the regal focal point. Ultra-realistic 4K, sharp details, radiant festival lighting, luxurious editorial vibe, bright dreamy background with rich red and golden tones. "
  },
  {
    id: 28,
    title: 'Kiểu 28 - Dáng Ngọc Đêm Rằm',
    text: "Keep my real face exactly the same as in the uploaded photo, do not change any facial features. A festive Mid-Autumn Festival indoor scene. A beautiful young Vietnamese woman with fair skin, an oval face, high cheekbones, and a delicate jawline. She has a confident, alluring expression, with dark brown hair styled in a neat low bun and a few soft strands framing her face. She has a graceful, feminine figure with a full, natural bust and a gentle cleavage that enhances her curves elegantly. She wears a luxurious haute couture evening gown inspired by the traditional yếm, made of shimmering golden satin silk. The halter neckline features an elegant cut-out that tastefully highlights her cleavage. The bodice is embroidered with golden lotus motifs and sparkling crystals, while the long flowing skirt drapes smoothly to the floor, balancing sensuality and sophistication. She is standing tall beside a bamboo table, lifting a glowing red lantern high above her head with one hand. The warm lantern light shines down, casting a golden glow across her gown and body, emphasizing her curves. With her other arm, she gently cradles a real fluffy white rabbit close to her chest. Her head is slightly tilted upward, her gaze lifted proudly, exuding the aura of a radiant moon goddess — both regal and sensual. On the bamboo table are golden mooncakes, sliced fruits, and a traditional brown ceramic teapot set. Around her are glowing lanterns in red, yellow, and green, and a black lacquer vase filled with blossoming peach flowers and red berries. In the background, a lion dance performance takes place beneath the large glowing full moon, intensifying the cinematic festive atmosphere. The overall mood is majestic, sensual, and celebratory, blending the essence of the Mid-Autumn Festival with the elegance of high-fashion editorial photography. Ultra-realistic 4K, sharp details, dramatic lantern lighting, rich red and golden tones. "
  },
  {
    id: 29,
    title: 'Kiểu 29 - Bóng Lưng Quyến Rũ',
    text: "Keep my real face exactly the same as in the uploaded photo, do not change any facial features. A cinematic full-body portrait during the Mid-Autumn Festival with a bright radiant background. A beautiful young Vietnamese woman is photographed from behind, walking gracefully toward the glowing full moon. Her long legs appear endless in the dramatic low-back perspective. She wears a haute couture evening gown inspired by the traditional yếm, made of shimmering golden satin silk with a refined halter cut-out neckline that highlights her curves. The gown is hand-embroidered with golden lotus motifs and sparkling crystals, flowing into a wide, floor-length skirt that spreads luxuriously across the ground. She turns her head elegantly over her shoulder, looking back toward the camera with a tender gaze. On her shoulder rests a real fluffy white rabbit, its eyes meeting hers affectionately. One hand is lifted softly, caressing the rabbit with warmth and tenderness. In the bright background, radiant red, yellow, and green lanterns glow vividly, a black lacquer vase with peach blossoms and red berries decorates the scene, and the silhouette of a lion dance troupe performs beneath the luminous full moon. The cinematic rim lighting outlines her figure and gown, creating a divine, goddess-like aura. Ultra-realistic 4K, sharp details, radiant festival lighting, flowing silk textures, dreamy and glamorous high-fashion editorial style. "
  },
  {
    id: 30,
    title: 'Kiểu 30 - Vẻ Đẹp Thần Tiên',
    text: "Keep my real face exactly the same as in the uploaded photo, do not change any facial features. A cinematic side-profile silhouette portrait during the Mid-Autumn Festival with a bright, radiant background. A beautiful young Vietnamese woman stands gracefully, her body turned sideways, revealing her elegant profile under the luminous full moon. The camera captures her side silhouette in glowing rim lighting, with the moonlight outlining her hair, jawline, and neckline. She wears a haute couture evening gown inspired by the traditional yếm, crafted from shimmering golden satin silk. The halter neckline features a tasteful cut-out that highlights her cleavage. The bodice is hand-embroidered with radiant golden lotus motifs and sparkling crystals, while the golden fabric drapes luxuriously down her figure, combining sensuality with elegance. She cradles a real fluffy white rabbit close to her chest, its fur glowing softly under the bright lantern and moonlight. Her posture is regal and serene, her profile exuding allure and the aura of a moon goddess. In the brightly illuminated background, glowing lanterns in red, yellow, and green shine vividly, a black lacquer vase filled with peach blossoms and red berries decorates the festive scene, and the silhouette of a lion dance troupe appears beneath the radiant full moon. The light and colors are vibrant, celebratory, and cinematic, with her silhouette remaining the focal point. Ultra-realistic 4K, sharp side-profile details, radiant festival lighting, bright dreamy background, rich tones of red and gold. "
  },
  {
    id: 31,
    title: 'Kiểu 31 - Góc Nghiêng Thần Thánh',
    text: "Keep my real face exactly the same as in the uploaded photo, do not change any facial features. A cinematic close-up portrait at a divine ¾ profile angle during the Mid-Autumn Festival. A beautiful young Vietnamese woman with fair skin, an oval face, high cheekbones, and a delicate jawline. Her head is slightly turned to the side, capturing her elegant profile in a “holy angle” pose that enhances her facial structure. She wears a haute couture evening gown inspired by the traditional yếm, crafted from shimmering golden satin silk. The halter neckline features a refined cut-out that tastefully highlights her cleavage. The bodice is hand-embroidered with radiant golden lotus motifs and sparkling crystals. The golden satin fabric drapes softly and luxuriously, balancing sensuality with refinement. She gently cradles a real fluffy white rabbit close to her chest, her hands tender and graceful. The focus is on her profile and the rabbit, with ultra-sharp details of her expression, skin texture, and the gown’s embroidery. In the softly blurred but visible background are glowing red, yellow, and green lanterns, a black lacquer vase filled with peach blossoms and red berries, and the silhouette of a lion dance under a glowing full moon. These dreamy festive elements create an artistic, cinematic atmosphere while keeping her profile and the rabbit as the focal point. Ultra-realistic 4K portrait, sharp profile details, cinematic lantern lighting, dreamy bokeh background, rich red and golden tones. "
  },
  {
    id: 32,
    title: 'Kiểu 32 - An Nhiên Tựa Bàn Trà',
    text: "Keep my real face exactly the same as in the uploaded photo, do not change any facial features. A festive Mid-Autumn Festival indoor scene. A beautiful young Vietnamese woman with fair skin, an oval face, high cheekbones, and a delicate jawline. She has a serene yet subtly alluring expression, with dark brown hair styled in a neat low bun and a few soft strands framing her face. She has a graceful, feminine figure with a full, natural bust and a gentle cleavage that enhances her curves elegantly. She wears a luxurious haute couture evening gown inspired by the traditional yếm. The gown is crafted from premium silk satin in a shimmering golden hue. Its halter neckline has a refined cut-out that reveals her soft cleavage in a tasteful way. The bodice is hand-embroidered with golden lotus motifs and decorated with tiny crystals. The floor-length skirt flows in elegant drapes, striking a balance between sensuality and sophistication. She is leaning slightly against a low bamboo table, her left hand resting lightly on its edge while her body remains relaxed. Her right arm holds a real fluffy white rabbit close to her chest. Her posture is elegant and natural, her gaze drifting into the distance with a dreamy expression, radiating both sensuality and refined grace. On the bamboo table are golden mooncakes, colorful sliced fruits, and a traditional brown ceramic teapot set with small cups. Surrounding her are glowing lanterns in red, yellow, and green, and a black lacquer vase filled with blossoming peach flowers and red berries. In the background, a lion dance performance unfolds beneath the large glowing full moon, enhancing the festive spirit. The overall mood is warm, dreamy, and celebratory, filled with the essence of the Mid-Autumn Festival. Cinematic lighting, ultra-realistic 4K photography, sharp details, rich red and golden tones. "
  },
  {
    id: 33,
    title: 'Kiểu 33 - Nửa Gương Mặt Kiều Diễm',
    text: "Keep my real face exactly the same as in the uploaded photo, do not change any facial features. An artistic half-face close-up portrait during the Mid-Autumn Festival. The camera frames only half of the woman’s face and half of the real fluffy white rabbit she is holding, creating a mysterious, editorial composition. She wears a haute couture evening gown inspired by the traditional yếm, crafted from shimmering golden satin silk. The halter neckline features a tasteful cut-out that highlights her cleavage. The bodice is embroidered with radiant golden lotus motifs and adorned with sparkling crystals. The golden fabric drapes softly, balancing sensuality with refined elegance. Her visible eye gazes directly into the camera, lips gently curved in a subtle half-smile, radiating allure and sophistication. In the softly blurred yet recognizable background are glowing lanterns in red, yellow, and green, a black lacquer vase filled with peach blossoms and red berries, and the silhouette of a lion dance under a large glowing full moon. These elements are dreamy but distinct, creating an atmospheric, cinematic Mid-Autumn Festival mood while keeping her face and the rabbit as the focal point. Ultra-realistic 4K, sharp facial details, cinematic lantern lighting, artistic bokeh background, rich red and golden tones. "
  },
  {
    id: 34,
    title: 'Kiểu 34 - Tỏa Sáng Cùng Lồng Đèn',
    text: "Keep my real face exactly the same as in the uploaded photo, do not change any facial features. A festive Mid-Autumn Festival indoor scene, framed in a half-body shot from the waist up. A beautiful young Vietnamese woman with fair skin, an oval face, high cheekbones, and a delicate jawline. She has a confident, alluring expression, with dark brown hair styled in a neat low bun and soft strands framing her face. She has a graceful figure with a natural full bust and gentle cleavage that enhances her curves elegantly. She wears a luxurious haute couture evening gown inspired by the traditional yếm, made of shimmering golden satin silk. The halter neckline has an elegant cut-out that highlights her cleavage tastefully. The bodice is embroidered with radiant golden lotus motifs and sparkling crystals, while the golden fabric drapes fluidly in soft folds, balancing sensuality and sophistication. She raises a glowing red lantern at shoulder level, the warm light casting a dramatic glow across her face and neckline. Her other arm cradles a real fluffy white rabbit close to her chest. Her expression is poised and regal, her gaze proud and confident, exuding the aura of a moon goddess. The subtle half-smile on her lips adds a high-fashion editorial charm, perfect for a Vogue magazine cover. Around her are glowing lanterns in red, yellow, and green, and a black lacquer vase filled with peach blossoms and red berries. The cinematic background includes a lion dance beneath the large glowing full moon, amplifying the festive spirit. The overall mood is glamorous, cinematic, and sensual — blending the warmth of the Mid-Autumn Festival with the elegance of high-fashion editorial. Ultra-realistic 4K, sharp details, dramatic lantern lighting, rich red and golden tones. "
  },
  {
    id: 35,
    title: 'Kiểu 35 - Thướt Tha Cầm Đèn',
    text: "Keep my real face exactly the same as in the uploaded photo, do not change any facial features. A cinematic half-body to full-body portrait during the Mid-Autumn Festival with a bright, radiant background. A beautiful young Vietnamese woman stands elegantly beside a bamboo table, her body slightly turned to the side. One hand gracefully holds a red lantern hanging low, while the other gently cradles a real fluffy white rabbit against her chest. Her posture is poised and refined, her gaze turned slightly away, exuding confidence and allure. She wears a haute couture evening gown inspired by the traditional yếm, made of shimmering golden satin silk. The halter neckline features a tasteful cut-out that accentuates her cleavage. The bodice is hand-embroidered with golden lotus motifs and adorned with sparkling crystals. The golden satin fabric flows luxuriously in a long skirt, draping softly around her figure, balancing sensuality with elegance. Beside her, the bamboo table displays golden mooncakes, colorful sliced fruits, and a traditional brown ceramic teapot set. In the brightly illuminated background, glowing red, yellow, and green lanterns shine vividly. A black lacquer vase filled with peach blossoms and red berries adds festive beauty, while the silhouette of a lion dance performance unfolds under a radiant full moon. The scene is cinematic, dreamy, and celebratory, with vibrant tones of red and gold bringing the Mid-Autumn Festival spirit to life. Ultra-realistic 4K, sharp details, radiant festival lighting, glamorous editorial vibe, bright dreamy background. "
  },
  {
    id: 36,
    title: 'Kiểu 36 - Kiêu Sa Cầm Đèn',
    text: "Keep my real face exactly the same as in the uploaded photo, do not change any facial features. A cinematic half-body to full-body portrait during the Mid-Autumn Festival with a bright, radiant background. A beautiful young Vietnamese woman stands elegantly beside a bamboo table, her body slightly turned to the side. One hand gracefully holds a red lantern hanging low, while the other gently cradles a real fluffy white rabbit against her chest. Her posture is poised and refined, her gaze turned slightly away, exuding confidence and allure. She wears a haute couture evening gown inspired by the traditional yếm, made of shimmering golden satin silk. The halter neckline features a tasteful cut-out that accentuates her cleavage. The bodice is hand-embroidered with golden lotus motifs and adorned with sparkling crystals. The golden satin fabric flows luxuriously in a long skirt, draping softly around her figure, balancing sensuality with elegance. Beside her, the bamboo table displays golden mooncakes, colorful sliced fruits, and a traditional brown ceramic teapot set. In the brightly illuminated background, glowing red, yellow, and green lanterns shine vividly. A black lacquer vase filled with peach blossoms and red berries adds festive beauty, while the silhouette of a lion dance performance unfolds under a radiant full moon. The scene is cinematic, dreamy, and celebratory, with vibrant tones of red and gold bringing the Mid-Autumn Festival spirit to life. Ultra-realistic 4K, sharp details, radiant festival lighting, glamorous editorial vibe, bright dreamy background. "
  },
  {
    id: 37,
    title: 'Kiểu 37 - Yếm Vàng & Lụa Là',
    text: "Keep my real face exactly the same as in the uploaded photo, do not change any facial features. A festive Mid-Autumn Festival indoor scene. A beautiful young Vietnamese woman with fair skin, an oval face, high cheekbones, and a delicate jawline. She has a serene yet subtly alluring expression, with dark brown hair styled in a neat low bun and a few soft strands framing her face. She has a graceful, feminine figure with a full, natural bust and a gentle cleavage that enhances her curves elegantly. She wears a luxurious haute couture evening gown inspired by the traditional yếm, made of shimmering golden silk satin. The halter neckline features a refined cut-out that highlights her cleavage naturally and tastefully. The bodice is hand-embroidered with radiant golden lotus motifs and adorned with sparkling crystals. The long floor-length skirt drapes smoothly, flowing gracefully as she moves, balancing sensuality with sophistication. She is standing elegantly beside a low bamboo table, her body slightly turned to the side and back, creating a refined, magazine-cover silhouette. In one hand, she holds a glowing red lantern hanging low, while her other arm gently cradles a real fluffy white rabbit against her chest. The golden gown cascades to the floor in soft folds, the light reflecting off the fabric to emphasize its sheen, as if illuminated for a fashion editorial. On the bamboo table are golden mooncakes, sliced colorful fruits, and a traditional brown ceramic teapot set. Around her, glowing lanterns in red, yellow, and green add festive warmth, while a black lacquer vase holds blossoming peach flowers and red berries. In the background, a lion dance performance takes place beneath the large glowing full moon, creating a vibrant Mid-Autumn Festival spirit. The overall mood is luxurious, cinematic, and celebratory, blending traditional festivity with high-fashion editorial elegance. Ultra-realistic 4K photography, sharp details, dramatic lighting on the flowing gown, rich red and golden tones. "
  },
  {
    id: 38,
    title: 'Kiểu 38 - Dáng Ngọc Hướng Trăng',
    text: "Keep my real face exactly the same as in the uploaded photo, do not change any facial features. A cinematic full-body portrait during the Mid-Autumn Festival with a bright radiant background. A beautiful young Vietnamese woman is photographed from behind, walking gracefully toward the glowing full moon. Her long legs appear endless in the dramatic low-back perspective. She wears a haute couture evening gown inspired by the traditional yếm, made of shimmering golden satin silk with a refined halter cut-out neckline that highlights her curves. The gown is hand-embroidered with golden lotus motifs and sparkling crystals, flowing into a wide, floor-length skirt that spreads luxuriously across the ground. She turns her head elegantly over her shoulder, looking back toward the camera with a tender gaze. On her shoulder rests a real fluffy white rabbit, its eyes meeting hers affectionately. One hand is lifted softly, caressing the rabbit with warmth and tenderness. In the bright background, radiant red, yellow, and green lanterns glow vividly, a black lacquer vase with peach blossoms and red berries decorates the scene, and the silhouette of a lion dance troupe performs beneath the luminous full moon. The cinematic rim lighting outlines her figure and gown, creating a divine, goddess-like aura. Ultra-realistic 4K, sharp details, radiant festival lighting, flowing silk textures, dreamy and glamorous high-fashion editorial style. "
  },
  {
    id: 39,
    title: 'Kiểu 39 - Nữ Thần Hoàng Gia',
    text: "Keep my real face exactly the same as in the uploaded photo, do not change any facial features. A festive Mid-Autumn Festival indoor scene. A beautiful young Vietnamese woman with fair skin, an oval face, high cheekbones, and a delicate jawline. She has a serene yet subtly alluring expression, with dark brown hair styled in a neat low bun and a few soft strands framing her face. She has a graceful, feminine figure with a full, natural bust and a gentle cleavage that enhances her curves elegantly. She wears a luxurious royal silk set in shimmering golden yellow. The outfit consists of a golden silk crop top with a halter neckline that subtly reveals her curves, paired with a long flowing skirt with a high slit, draped with a sheer golden mesh overlay that sparkles under the lantern light. Tiny crystals are delicately embedded into the fabric, reflecting the glow of the lanterns with a regal brilliance. She is standing beside a low bamboo table, her left hand resting lightly on the edge of the table while her right arm holds a real fluffy white rabbit close to her chest. The high slit of her skirt reveals her long, slender legs, and the golden fabric flows gracefully, fluttering as if stirred by the warm breeze from the glowing lanterns. This elegant pose accentuates her tall figure, making her look like a radiant queen of the moon. On the bamboo table are golden mooncakes, neatly sliced fruits, and a traditional brown ceramic teapot set with small cups. Surrounding the scene are vibrant lanterns in red, yellow, and green, and a black lacquer vase filled with blossoming peach flowers and red berries. In the background, a lion dance performance takes place under a large glowing full moon, adding energy and festivity to the atmosphere. The overall mood is warm, dreamy, and celebratory, filled with the essence of the Mid-Autumn Festival. Cinematic lighting, ultra-realistic 4K photography, sharp details, rich red and golden tones. "
  },
  {
    id: 40,
    title: 'Kiểu 40 - Vẻ Đẹp Thư Thái',
    text: "Keep my real face exactly the same as in the uploaded photo, do not change any facial features. A festive Mid-Autumn Festival indoor scene. A beautiful young Vietnamese woman with fair skin, an oval face, high cheekbones, and a delicate jawline. She has a serene yet alluring expression, with dark brown hair styled in a neat low bun and a few soft strands framing her face. She has a graceful, feminine figure with a full, natural bust and a gentle cleavage that enhances her curves elegantly. She wears a luxurious haute couture evening gown inspired by the traditional yếm, made of shimmering golden satin silk. The halter neckline features a tasteful cut-out that highlights her cleavage naturally. The bodice is embroidered with golden lotus motifs and delicate sparkling crystals, while the floor-length skirt flows in graceful drapes with a high slit, combining sensuality with sophistication. She is sitting casually on a bamboo mat, one leg stretched out and the other bent slightly, revealing her elegant curves. A real fluffy white rabbit rests gently on her lap as her hand softly caresses it. The gown’s flowing fabric spreads across the bamboo mat around her, glowing under the lantern light. Her face is illuminated by the warm glow, her dreamy eyes gazing softly, radiating an aura that feels both intimate and sensual. Around her are glowing lanterns in red, yellow, and green, and a black lacquer vase filled with blossoming peach flowers and red berries. In front of her is a low bamboo table with golden mooncakes, colorful sliced fruits, and a traditional brown ceramic teapot set. In the background, a lion dance performance takes place under the large glowing full moon, filling the space with vibrance and festivity. The overall mood is warm, intimate, and cinematic — close, natural, yet alluring. Ultra-realistic 4K, sharp details, dramatic lantern lighting, rich red and golden tones. "
  }
];


export const MALE_PROMPTS = [
  {
    id: 1,
    title: 'Kiểu 1 – Selfie Lồng Đèn',
    text: "Keep 100% of the character's face from the uploaded photo. A young man in a modern, ruby red brocade ao dai. Stylishly groomed hair. Holding a traditional red lantern for a close-up selfie, with a charming gaze. Background: a row of high-hanging red lanterns with warm golden light. Vibe: elegant – charming – Mid-Autumn Festival.",
  },
  {
    id: 2,
    title: 'Kiểu 2 – Bánh Nước & Trà',
    text: "Keep 100% of the character's face from the uploaded photo. Half-body shot, a young man sits at a bamboo table, wearing a red silk shirt, holding a mooncake, with a thoughtful look at the camera. Sharp, masculine features. Background: bamboo table, tea, red and gold mooncake box. Golden hour lighting. Vibe: masculine – lifestyle – Mid-Autumn Festival.",
  },
  {
    id: 3,
    title: 'Kiểu 3 – Sải Bước Đường Phố',
    text: "Keep 100% of the character's face from the uploaded photo. Full-body low angle, a young man strides confidently on a lantern-lit street in Hoi An. Wearing a wine-red suit, polished leather shoes. Neatly styled hair. A confident walk, looking straight ahead with charisma. Background: a sparkling street of red and yellow lanterns. Vibe: elegant – high fashion – Mid-Autumn Festival.",
  },
  {
    id: 4,
    title: 'Kiểu 4 – Ánh Trăng Sân Thượng',
    text: "Keep 100% of the character's face from the uploaded photo. Cinematic photo, a young man stands on a rooftop, wearing a red leather jacket, with the full moon behind him. Holding a lantern, gazing into the distance. A strong posture. Background: city skyline with the Mid-Autumn moon. Vibe: magical – masculine – romantic.",
  },
];
